# Default values for orchestrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

kairosdb:
  image:
    repository: gcmcnutt/docker-kairosdb
    tag: gmcnutt-0.8.6-SNAPSHOT

#    datastoreReplicationFactor: 1
#
#    # quote these... https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/values.md
#    memoryQueueSize: "200000"
#    defaultTtl: "3024000"
#    queueProcessor: org.kairosdb.core.queue.FileQueueProcessor
#    queryThreads: 20

  connectLocalDB: true

  service:
    name: kairosdb
    type: NodePort
    externalPort: 8080
    internalPort: 8080
    probeTimeoutSeconds: 5
    initialDelaySeconds: 30

  resources: {}

persistence:
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  # if set, a PVC will also be allocated
  # size: 1Gi

global:
  image:
    repositoryPrefix:
    pullPolicy: IfNotPresent
