# Default values for orchestrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

scylladb:
  image:
    repository: gcmcnutt/scylladb
    tag: v0.6.5

  config:
    overprovisioned: 1
    maxIORequests: 256
    batchSizeWarnKb: 50
    batchSizeFailKb: 70
#    cpu: 1
#    memory: 500M

  service:
    cqlNativePort: 9042
    thriftPort: 9160
    internodePort: 7000
    jmxPort: 7199
    scyllaRestPort: 10000
    prometheusPort: 9180

    probeTimeoutSeconds: 10
    initialDelaySeconds: 30

  resources: {}

kairosdb:
  image:
    repository: gcmcnutt/kairosdb
    tag: v0.6.4

  queueProcessorBatchSize: 10000

  service:
    name: kairosdb
    type: NodePort
    externalPort: 8080
    internalPort: 8080
    probeTimeoutSeconds: 5
    initialDelaySeconds: 30

  resources: {}

persistence:
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  # if set, a PVC will also be allocated
  # size: 1Gi

global:
  image:
    repositoryPrefix:
    pullPolicy: IfNotPresent
