apiVersion: v1
kind: Service
metadata:
  name: {{ template "scylladb.fullname" . }}
  labels:
    app: {{ template "scylladb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.cqlNativePort }}
      name: cql
    - port: {{ .Values.service.thriftPort }}
      name: thrift
    - port: {{ .Values.service.internodePort }}
      name: internode
    - port: {{ .Values.service.jmxPort }}
      name: jmx
    - port: {{ .Values.service.scyllaRestPort }}
      name: rest
    - port: {{ .Values.service.prometheusPort }}
      name: prometheus
  selector:
    app: {{ template "scylladb.name" . }}
    release: {{ .Release.Name }}

