apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kairosdb.fullname" . }}
  labels:
    app: {{ template "kairosdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kairosdb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "kairosdb.imageId" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            timeoutSeconds: {{ .Values.service.probeTimeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            timeoutSeconds: {{ .Values.service.probeTimeoutSeconds }}
          volumeMounts:
            - name: configmap
              mountPath: /opt/kairosdb/conf/kairosdb.properties
              subPath: kairosdb.properties
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: configmap
        configMap:
          name: {{ template "kairosdb.fullname" . }}
