apiVersion: v1
kind: Service
metadata:
  # TODO figure out why the DNS isn't following the doc and we have to name override here!
  # (hint: if we have the service name different from stateful set name, things aren't working)
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
  name: {{ template "kairosdb.fullname" . }}-app
  labels:
    app: {{ template "kairosdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.kairosdb.annotations }}
  annotations:
{{ toYaml .Values.kairosdb.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.kairosdb.service.type }}
  ports:
    - port: {{ .Values.kairosdb.service.externalPort }}
      targetPort: {{ .Values.kairosdb.service.internalPort }}
      protocol: TCP
      name: {{ .Values.kairosdb.service.name }}
  selector:
    app: {{ template "kairosdb.name" . }}
    release: {{ .Release.Name }}
