apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "kairosdb.fullname" . }}
  labels:
    app: {{ template "kairosdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "kairosdb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kairosdb.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}

      containers:
      - name: scylladb
        image: {{ template "kairosdb.scyllaImageId" . }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.scylladb.service.cqlNativePort }}
          - containerPort: {{ .Values.scylladb.service.thriftPort }}
          - containerPort: {{ .Values.scylladb.service.internodePort }}
          - containerPort: {{ .Values.scylladb.service.jmxPort }}
          - containerPort: {{ .Values.scylladb.service.scyllaRestPort }}
          - containerPort: {{ .Values.scylladb.service.prometheusPort }}
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_STATEFULSET_NAME
          value: {{ template "kairosdb.fullname" . }}
        args:
          - --cluster-name
          - {{ template "kairosdb.fullname" . }}
          - --max-io-requests
          - {{ .Values.scylladb.config.maxIORequests | quote }}
          {{- if .Values.scylladb.config.batchSizeWarnKb }}
          - --batch-size-warn-threshold-in-kb
          - {{ .Values.scylladb.config.batchSizeWarnKb | quote }}
          {{- end }}
          {{- if .Values.scylladb.config.batchSizeFailKb }}
          - --batch-size-fail-threshold-in-kb
          - {{ .Values.scylladb.config.batchSizeFailKb | quote }}
          {{- end }}
          {{- if .Values.scylladb.config.overprovisioned }}
          - --overprovisioned
          {{- end }}
          {{- if .Values.scylladb.config.cpu }}
          - --smp
          - {{ .Values.scylladb.config.cpu | quote }}
          {{- end }}
          {{- if .Values.scylladb.config.memory }}
          - --memory
          - {{ .Values.scylladb.config.memory | quote }}
          {{- end }}
          {{- if .Values.scylladb.config.endpointSnitch }}
          - --endpoint-snitch
          - {{ .Values.scylladb.config.endpointSnitch | quote }}
          {{- end }}
        {{- if .Values.persistence.size }}
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/scylla
        {{- end }}
        livenessProbe:
          exec:
            command:
              - nodetool
              - status
          initialDelaySeconds: {{ .Values.scylladb.service.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.scylladb.service.probeTimeoutSeconds }}
        readinessProbe:
          exec:
            command:
              - nodetool
              - status
          initialDelaySeconds: {{ .Values.scylladb.service.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.scylladb.service.probeTimeoutSeconds }}
        resources:
{{ toYaml .Values.scylladb.resources | indent 10 }}

      - name: kairosdb
        image: {{ template "kairosdb.kairosImageId" . }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.kairosdb.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.kairosdb.service.internalPort }}
          initialDelaySeconds: {{ .Values.kairosdb.service.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.kairosdb.service.probeTimeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.kairosdb.service.internalPort }}
          initialDelaySeconds: {{ .Values.kairosdb.service.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.kairosdb.service.probeTimeoutSeconds }}
        env:
        - name: SEEDS
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPLICATION_FACTOR
          value: {{ .Values.kairosdb.datastoreReplicationFactor | default "1" | quote }}
{{- if .Values.persistence.size }}
        volumeMounts:
        - name: datadir
          mountPath: /data
{{- end }}
        resources:
{{ toYaml .Values.kairosdb.resources | indent 10 }}

{{- if .Values.persistence.size }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      {{- end }}
{{- end }}
