# aws configuration

replicaCount: 3

persistence:
  size: 4Ti
  storageClass: pure

scylladb:
  config:
    overprovisioned: 0
    cpu: 4
    memory: 4G
    endpointSnitch: Ec2Snitch

  resources:
    requests:
      cpu: 4000m
      memory: 4Gi

kairosdb:

  datastoreReplicationFactor: 3

  queueProcessor: org.kairosdb.core.queue.MemoryQueueProcessor
  defaultTtl: "86400"
  memoryQueueSize: "1000000"

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'

  service:
    type: LoadBalancer
    externalPort: 80

  resources:
    requests:
      cpu: 2000m
      memory: 2Gi

global:
  image:
    pullPolicy: Always