# aws configuration
#global:
#  image:
#    repositoryPrefix: XXX.dkr.ecr.us-west-2.amazonaws.com
#    pullPolicy: Always

replicaCount: 3

datastoreReplicationFactor: 3

resources:
  requests:
    cpu: 1000m
    memory: 1Gi

annotations:
  service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'

service:
  type: LoadBalancer
  externalPort: 80


scylladb:
  config:
    overprovisioned: 0
    cpu: 2
    memory: 2G
    endpointSnitch: Ec2Snitch

  replicaCount: 6

  persistence:
    size: 50Gi
#    storageClass: io1

  resources:
    requests:
      cpu: 2000m
      memory: 2Gi

